### ISSUE TITLE
Run errors on EasyHbrid3 

### ISSUE THREAD

**Issue by chaoyangma24** [ferbachega/EasyHybrid3#1]
Thank for your EasyHybrid3. 
Installing it successfully by "python (python3.9) install.py", there appeared the following errors when run it by " python Easyhybrid.py “ .  I want to know the resolving methods. Your answer would be very appreciated!

Traceback (most recent call last):
  File "/home/chaoyang/soft/umbrella/EasyHybrid3-main/Easyhybrid.py", line 94, in <module>
    from pdynamo.pDynamo2EasyHybrid import pDynamoSession
  File "/home/chaoyang/soft/umbrella/EasyHybrid3-main/pdynamo/pDynamo2EasyHybrid.py", line 36, in <module>
    from vismol.model.residue import Residue
ModuleNotFoundError: No module named 'vismol'

**Comment by ferbachega** [comment]
Hello! I apologize as I just saw your message now. If you're still interested, I'd be happy to help.

Have you tried the most current version? There is an installation tutorial on the website:
https://sites.google.com/view/easyhybrid/home
Let me know if you have problems or suggestions.

Cheers!

**Comment by chaoyangma24** [comment]
Dear Professor&nbsp;Fernando&nbsp;


&nbsp; Thank for your kind reply. I will install it according to your advice. Thank you again!


Best regards
Dr Ma
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Aug 28, 2023 10:06 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ferbachega/EasyHybrid3] Run errors on EasyHbrid3  (Issue #1)

&nbsp;



 
Hello! I apologize as I just saw your message now. If you're still interested, I'd be happy to help.
 
Have you tried the most current version? There is an installation tutorial on the website:
 https://sites.google.com/view/easyhybrid/home
 Let me know if you have problems or suggestions.
 
Cheers!
